/**
 * Shared mood emoji options used by Diary and Thoughts content types.
 * Value-only entries render the emoji as both the stored value and display.
 */
export const MOOD_OPTIONS = [
  { value: "☀️" },
  { value: "🌤️" },
  { value: "🌞" },
  { value: "🌈" },
  { value: "🌧️" },
  { value: "🌦️" },
  { value: "🌩️" },
  { value: "🌨️" },
  { value: "❄️" },
  { value: "🍃" },
  { value: "🍂" },
  { value: "🍁" },
  { value: "🌇" },
  { value: "🌙" },
  { value: "🌝" },
  { value: "🌫️" },
  { value: "😶‍🌫️" },
  { value: "🧺" },
  { value: "🪴" },
  { value: "🍵" },
  { value: "📚" },
  { value: "🎨" },
  { value: "💡" },
  { value: "💭" },
  { value: "☕" },
  { value: "✂️" },
  { value: "🧩" },
  { value: "✨" },
  { value: "🫧" },
  { value: "🤍" },
  { value: "😊" },
  { value: "🙂" },
  { value: "😌" },
  { value: "😎" },
  { value: "🤗" },
  { value: "🥰" },
  { value: "😍" },
  { value: "🤔" },
  { value: "🙃" },
  { value: "😴" },
  { value: "😭" },
  { value: "😤" },
  { value: "🤪" },
  { value: "😵" },
  { value: "🫶" },
  { value: "🪄" },
  { value: "🪁" },
  { value: "🛠️" },
] as const;

/** Weather options for the Diary content type. */
export const WEATHER_OPTIONS = [
  { value: "sunny", labelKey: "diary.weatherSunny" },
  { value: "cloudy", labelKey: "diary.weatherCloudy" },
  { value: "fog", labelKey: "diary.weatherFog" },
  { value: "haze", labelKey: "diary.weatherHaze" },
  { value: "light_rain", labelKey: "diary.weatherLightRain" },
  { value: "shower", labelKey: "diary.weatherShower" },
  { value: "heavy_rain", labelKey: "diary.weatherHeavyRain" },
  { value: "light_snow", labelKey: "diary.weatherLightSnow" },
  { value: "heavy_snow", labelKey: "diary.weatherHeavySnow" },
  { value: "sleet", labelKey: "diary.weatherSleet" },
  { value: "stormy", labelKey: "diary.weatherStormy" },
  { value: "windy", labelKey: "diary.weatherWindy" },
] as const;
