export type FieldInputKind = "text「 | 」textarea「 | 」number「 | 」select「 | 」list";
export type FieldSource = "base「 | 」extra";

export interface PageFieldDefinition {
  key: string;
  source: FieldSource;
  input: FieldInputKind;
  label: string;
  helpTitle: string;
  helpDescription: string;
  usageItems: string[];
  optional?: boolean;
  placeholder?: string;
  options?: Array<{ value: string; label: string }>;
}

export const WIDTH_OPTIONS = [
  { value: "「, label: 」自动跟随默认宽度" },
  { value: "max-w-2xl「, label: 」窄版内容宽度" },
  { value: "max-w-3xl「, label: 」标准内容宽度" },
  { value: "max-w-4xl「, label: 」宽版内容宽度" },
];

export const SHARED_FIELDS: PageFieldDefinition[] = [
  {
    key: "title",
    source: "base",
    input: "text",
    label: "页面主标题",
    helpTitle: "页面最醒目的标题",
    helpDescription: "用于页面头部的大号标题，是访客进入这个页面时最先看到的名称。",
    usageItems: [
      "页面头部的大标题",
      "部分详情页或预览场景的标题兜底",
    ],
  },
  {
    key: "subtitle",
    source: "base",
    input: "textarea",
    label: "页面导语",
    helpTitle: "页面标题下方的主要说明文案",
    helpDescription: "这是一段直接展示给访客的介绍文字。当前前台会优先把它作为页面描述来渲染。",
    usageItems: [
      "页面头部标题下方的介绍文字",
      "访客理解页面内容和语气的第一段说明",
    ],
  },
  {
    key: "eyebrow",
    source: "extra",
    input: "text",
    label: "标题上方小标签",
    helpTitle: "标题上方的小号提示标签",
    helpDescription: "适合放分类名、栏目名或气氛说明。留空时页面头部不会显示这一行。",
    usageItems: [
      "页面标题上方的小号英文/短标签",
    ],
    optional: true,
  },
  {
    key: "metaTitle",
    source: "extra",
    input: "text",
    label: "SEO / 分享标题",
    helpTitle: "浏览器标题和分享标题",
    helpDescription: "如果填写这里，会优先用于页面浏览器标题、分享卡片标题和部分 SEO 标题。",
    usageItems: [
      "浏览器标签页标题",
      "页面分享卡片标题",
      "页面 SEO 标题",
    ],
    optional: true,
  },
  {
    key: "metaDescription",
    source: "extra",
    input: "textarea",
    label: "SEO / 分享描述",
    helpTitle: "页面在分享或搜索结果里的简介",
    helpDescription: "不会直接出现在页面正文里，主要用于分享卡片和搜索引擎描述。",
    usageItems: [
      "Open Graph / Twitter 描述",
      "页面 SEO 描述",
    ],
    optional: true,
  },
  {
    key: "description",
    source: "base",
    input: "textarea",
    label: "内部备注",
    helpTitle: "给管理端看的补充说明",
    helpDescription: "这个字段现在主要作为配置备注使用，不再优先作为访客可见的页面简介。只有在页面导语为空时，前台才会拿它兜底。",
    usageItems: [
      "管理端说明和后续维护备注",
      "页面导语为空时的描述兜底",
    ],
    optional: true,
  },
  {
    key: "empty_message",
    source: "base",
    input: "textarea",
    label: "空状态文案",
    helpTitle: "页面没有内容时显示的提示",
    helpDescription: "当列表为空、当前日期没有记录，或筛选后没有结果时，会显示这段文案。",
    usageItems: [
      "页面列表为空时的提示",
      "部分页面筛选无结果时的提示",
    ],
    optional: true,
  },
  {
    key: "search_placeholder",
    source: "base",
    input: "text",
    label: "搜索框提示词",
    helpTitle: "搜索输入框里的占位提示",
    helpDescription: "适用于有搜索框的页面，目前主要会影响文章列表页。",
    usageItems: [
      "搜索输入框 placeholder",
      "搜索框辅助 aria 文案兜底",
    ],
    optional: true,
  },
  {
    key: "max_width",
    source: "base",
    input: "select",
    label: "页面内容宽度",
    helpTitle: "页面主体容器的最大宽度",
    helpDescription: "控制这一页整体的排版宽窄。窄版更适合阅读，宽版更适合网格和数据块。",
    usageItems: [
      "页面主内容区域的横向宽度",
    ],
    optional: true,
    options: WIDTH_OPTIONS,
  },
  {
    key: "page_size",
    source: "base",
    input: "number",
    label: "每次加载条数",
    helpTitle: "分页或无限滚动每次请求的条目数",
    helpDescription: "适用于文章、日记、碎碎念、文摘等列表页。数值越大，单次请求内容越多。",
    usageItems: [
      "列表页的分页大小",
      "无限滚动一次追加的内容数量",
    ],
    optional: true,
  },
  {
    key: "download_label",
    source: "base",
    input: "text",
    label: "下载按钮文案",
    helpTitle: "页面里的下载按钮文字",
    helpDescription: "主要用于简历页下载按钮，其他页面如果未来接入下载动作也可复用。",
    usageItems: [
      "简历页下载按钮",
    ],
    optional: true,
  },
];

export const PAGE_SPECIFIC_FIELDS: Record<string, PageFieldDefinition[]> = {
  activity: [
    {
      key: "dashboardLabel",
      source: "extra",
      input: "text",
      label: "首页活动区眉标题",
      helpTitle: "首页活动区标题上方的小标签",
      helpDescription: "用于首页活动区左上角的小号栏目名。",
      usageItems: [
        "首页 Activity Section 顶部小标签",
      ],
      optional: true,
    },
    {
      key: "friendCircleTitle",
      source: "extra",
      input: "text",
      label: "首页友邻区标题",
      helpTitle: "首页活动区左侧卡片的标题",
      helpDescription: "控制首页友邻动态卡片顶部标题。",
      usageItems: [
        "首页 Friend Circle 卡片标题",
      ],
      optional: true,
    },
    {
      key: "friendCircleViewAllLabel",
      source: "extra",
      input: "text",
      label: "首页友邻区「查看全部」按钮",
      helpTitle: "首页友邻卡片跳转按钮文案",
      helpDescription: "点击后会进入完整友链页。",
      usageItems: [
        "首页 Friend Circle 卡片右上角按钮",
      ],
      optional: true,
    },
    {
      key: "friendCircleErrorTitle",
      source: "extra",
      input: "text",
      label: "首页友邻区加载失败标题",
      helpTitle: "首页友邻动态接口失败时的标题",
      helpDescription: "当首页友邻动态请求失败时显示。",
      usageItems: [
        "首页 Friend Circle 错误状态标题",
      ],
      optional: true,
    },
    {
      key: "friendCircleRetryLabel",
      source: "extra",
      input: "text",
      label: "首页友邻区重试按钮",
      helpTitle: "首页友邻动态重试按钮文案",
      helpDescription: "用于首页友邻卡片错误状态下的重试按钮。",
      usageItems: [
        "首页 Friend Circle 错误状态按钮",
      ],
      optional: true,
    },
    {
      key: "friendCircleEmptyMessage",
      source: "extra",
      input: "textarea",
      label: "首页友邻区空状态文案",
      helpTitle: "首页友邻动态为空时的提示",
      helpDescription: "当没有公开友邻动态时显示。",
      usageItems: [
        "首页 Friend Circle 空状态",
      ],
      optional: true,
    },
    {
      key: "recentActivityTitle",
      source: "extra",
      input: "text",
      label: "首页最近动态标题",
      helpTitle: "首页活动区右侧卡片标题",
      helpDescription: "控制最近动态卡片的标题。",
      usageItems: [
        "首页 Recent Activity 卡片标题",
      ],
      optional: true,
    },
    {
      key: "recentActivityErrorTitle",
      source: "extra",
      input: "text",
      label: "首页最近动态加载失败标题",
      helpTitle: "最近动态接口失败时的标题",
      helpDescription: "用于首页最近动态卡片错误状态。",
      usageItems: [
        "首页 Recent Activity 错误状态标题",
      ],
      optional: true,
    },
    {
      key: "recentActivityRetryLabel",
      source: "extra",
      input: "text",
      label: "首页最近动态重试按钮",
      helpTitle: "最近动态错误状态下的按钮文案",
      helpDescription: "用于首页最近动态卡片的重试操作。",
      usageItems: [
        "首页 Recent Activity 错误状态按钮",
      ],
      optional: true,
    },
    {
      key: "recentActivityEmptyMessage",
      source: "extra",
      input: "textarea",
      label: "首页最近动态空状态文案",
      helpTitle: "最近动态为空时的提示",
      helpDescription: "当首页没有可展示的最近动态时显示。",
      usageItems: [
        "首页 Recent Activity 空状态",
      ],
      optional: true,
    },
    {
      key: "heatmapTitle",
      source: "extra",
      input: "text",
      label: "热力图标题",
      helpTitle: "首页底部热力图主标题",
      helpDescription: "控制热力图模块左上角标题。",
      usageItems: [
        "首页 Activity Heatmap 标题",
      ],
      optional: true,
    },
    {
      key: "heatmapLoadingLabel",
      source: "extra",
      input: "text",
      label: "热力图加载中文案",
      helpTitle: "热力图请求中时的状态文案",
      helpDescription: "在热力图尚未返回数据时显示。",
      usageItems: [
        "首页 Activity Heatmap 状态栏",
      ],
      optional: true,
    },
    {
      key: "heatmapErrorLabel",
      source: "extra",
      input: "text",
      label: "热力图加载失败文案",
      helpTitle: "热力图请求失败时的状态文案",
      helpDescription: "用于热力图模块顶部状态区。",
      usageItems: [
        "首页 Activity Heatmap 状态栏",
      ],
      optional: true,
    },
    {
      key: "heatmapTotalTemplate",
      source: "extra",
      input: "text",
      label: "热力图总量模板",
      helpTitle: "热力图顶部总量统计文案模板",
      helpDescription: "支持 `{total}` 占位符，例如：`共 {total} 次记录`。",
      usageItems: [
        "首页 Activity Heatmap 顶部总量数字说明",
      ],
      optional: true,
      placeholder: "共 {total} 次记录",
    },
    {
      key: "heatmapThisWeekLabel",
      source: "extra",
      input: "text",
      label: "热力图「本周」标签",
      helpTitle: "热力图统计项一的标签文字",
      helpDescription: "用于第一项统计指标的名称。",
      usageItems: [
        "首页 Activity Heatmap 统计指标",
      ],
      optional: true,
    },
    {
      key: "heatmapPeakWeekLabel",
      source: "extra",
      input: "text",
      label: "热力图「峰值周」标签",
      helpTitle: "热力图统计项二的标签文字",
      helpDescription: "用于第二项统计指标的名称。",
      usageItems: [
        "首页 Activity Heatmap 统计指标",
      ],
      optional: true,
    },
    {
      key: "heatmapAverageWeekLabel",
      source: "extra",
      input: "text",
      label: "热力图「周平均」标签",
      helpTitle: "热力图统计项三的标签文字",
      helpDescription: "用于第三项统计指标的名称。",
      usageItems: [
        "首页 Activity Heatmap 统计指标",
      ],
      optional: true,
    },
  ],
  notFound: [
    {
      key: "badgeLabel",
      source: "extra",
      input: "text",
      label: "404 徽标文字",
      helpTitle: "404 页面卡片顶部的小标签",
      helpDescription: "默认是偏技术感的小标识，建议写成短词组。",
      usageItems: [
        "404 页面顶部徽标",
      ],
      optional: true,
    },
    {
      key: "homeLabel",
      source: "extra",
      input: "text",
      label: "404「返回首页」按钮",
      helpTitle: "404 页面主按钮文案",
      helpDescription: "控制 404 页面主操作按钮的文字。",
      usageItems: [
        "404 页面主按钮",
      ],
      optional: true,
    },
    {
      key: "backLabel",
      source: "extra",
      input: "text",
      label: "404「返回上页」按钮",
      helpTitle: "404 页面次按钮文案",
      helpDescription: "控制 404 页面返回上一级的按钮文字。",
      usageItems: [
        "404 页面次按钮",
      ],
      optional: true,
    },
  ],
  posts: [
    {
      key: "errorTitle",
      source: "extra",
      input: "text",
      label: "文章页加载失败标题",
      helpTitle: "文章列表接口失败时的标题",
      helpDescription: "用于文章列表页的错误状态主标题。",
      usageItems: [
        "文章列表错误状态",
      ],
      optional: true,
    },
    {
      key: "retryLabel",
      source: "extra",
      input: "text",
      label: "文章页重试按钮",
      helpTitle: "文章列表页重试按钮文案",
      helpDescription: "用于文章列表页错误状态和文章详情错误状态。",
      usageItems: [
        "文章列表错误状态按钮",
        "文章详情错误状态按钮",
      ],
      optional: true,
    },
    {
      key: "loadMoreLabel",
      source: "extra",
      input: "text",
      label: "文章页加载更多文案",
      helpTitle: "文章列表滚动加载时的提示",
      helpDescription: "当文章列表还有更多内容时使用。",
      usageItems: [
        "文章列表底部的加载更多提示",
      ],
      optional: true,
    },
    {
      key: "category_all_label",
      source: "extra",
      input: "text",
      label: "文章分类「全部」标签",
      helpTitle: "文章分类筛选里的「全部「名称",
      helpDescription: "用于文章列表分类切换按钮的第一个选项。",
      usageItems: [
        "文章列表分类筛选",
      ],
      optional: true,
    },
    {
      key: "category_fallback_label",
      source: "extra",
      input: "text",
      label: "文章分类缺省标签",
      helpTitle: "文章没有分类时的兜底名称",
      helpDescription: "当文章本身没有分类字段时显示。",
      usageItems: [
        "文章卡片分类兜底",
        "文章详情分类兜底",
      ],
      optional: true,
    },
    {
      key: "detailBackLabel",
      source: "extra",
      input: "text",
      label: "文章详情返回按钮",
      helpTitle: "文章详情页左上角返回按钮文案",
      helpDescription: "控制文章详情页返回上一页按钮的文字。",
      usageItems: [
        "文章详情页顶部返回按钮",
      ],
      optional: true,
    },
    {
      key: "detailListLabel",
      source: "extra",
      input: "text",
      label: "文章详情「返回列表」按钮",
      helpTitle: "文章不存在时返回列表的按钮文案",
      helpDescription: "当文章不存在时显示在错误区块底部。",
      usageItems: [
        "文章详情空状态按钮",
      ],
      optional: true,
    },
    {
      key: "detailMissingTitle",
      source: "extra",
      input: "text",
      label: "文章详情不存在标题",
      helpTitle: "文章不存在时的标题",
      helpDescription: "用于文章详情 404 或内容不存在的场景。",
      usageItems: [
        "文章详情空状态标题",
      ],
      optional: true,
    },
    {
      key: "detailMissingDescription",
      source: "extra",
      input: "textarea",
      label: "文章详情不存在说明",
      helpTitle: "文章不存在时的补充说明",
      helpDescription: "用于文章详情页找不到内容时的解释文字。",
      usageItems: [
        "文章详情空状态说明",
      ],
      optional: true,
    },
    {
      key: "detailEndLabel",
      source: "extra",
      input: "text",
      label: "文章详情结尾文案",
      helpTitle: "文章正文结束后的短句",
      helpDescription: "用于文章阅读结束后的收尾文案。",
      usageItems: [
        "文章详情正文结尾",
      ],
      optional: true,
    },
  ],
  diary: [
    {
      key: "errorTitle",
      source: "extra",
      input: "text",
      label: "日记页加载失败标题",
      helpTitle: "日记列表接口失败时的标题",
      helpDescription: "用于日记列表页错误状态的主标题。",
      usageItems: [
        "日记列表错误状态",
      ],
      optional: true,
    },
    {
      key: "retryLabel",
      source: "extra",
      input: "text",
      label: "日记页重试按钮",
      helpTitle: "日记列表与详情页的重试按钮文案",
      helpDescription: "会同时影响日记列表错误状态和日记详情错误状态。",
      usageItems: [
        "日记列表错误状态按钮",
        "日记详情错误状态按钮",
      ],
      optional: true,
    },
    {
      key: "loadMoreLabel",
      source: "extra",
      input: "text",
      label: "日记页加载更多文案",
      helpTitle: "日记列表底部滚动加载文案",
      helpDescription: "当还有更多日记未加载时显示。",
      usageItems: [
        "日记列表底部加载提示",
      ],
      optional: true,
    },
    {
      key: "detailCtaLabel",
      source: "extra",
      input: "text",
      label: "日记卡片「查看详情」按钮",
      helpTitle: "展开后的日记卡片跳转按钮文案",
      helpDescription: "用于日记列表中展开内容后的跳转按钮。",
      usageItems: [
        "日记列表卡片底部按钮",
      ],
      optional: true,
    },
    {
      key: "detailBackLabel",
      source: "extra",
      input: "text",
      label: "日记详情返回按钮",
      helpTitle: "日记详情页顶部返回按钮文案",
      helpDescription: "控制详情页左上角返回按钮文字。",
      usageItems: [
        "日记详情页顶部返回按钮",
      ],
      optional: true,
    },
    {
      key: "detailListLabel",
      source: "extra",
      input: "text",
      label: "日记详情「返回列表」按钮",
      helpTitle: "日记不存在时的返回列表按钮文案",
      helpDescription: "用于日记详情空状态底部按钮。",
      usageItems: [
        "日记详情空状态按钮",
      ],
      optional: true,
    },
    {
      key: "detailMissingTitle",
      source: "extra",
      input: "text",
      label: "日记详情不存在标题",
      helpTitle: "日记不存在时的标题",
      helpDescription: "用于日记详情找不到内容的场景。",
      usageItems: [
        "日记详情空状态标题",
      ],
      optional: true,
    },
    {
      key: "detailMissingDescription",
      source: "extra",
      input: "textarea",
      label: "日记详情不存在说明",
      helpTitle: "日记不存在时的说明文字",
      helpDescription: "用于日记详情空状态的解释说明。",
      usageItems: [
        "日记详情空状态说明",
      ],
      optional: true,
    },
    {
      key: "detailEndLabel",
      source: "extra",
      input: "text",
      label: "日记详情结尾文案",
      helpTitle: "日记正文底部的收尾短句",
      helpDescription: "用于日记阅读结束时的短文案。",
      usageItems: [
        "日记详情正文结尾",
      ],
      optional: true,
    },
  ],
  friends: [
    {
      key: "errorTitle",
      source: "extra",
      input: "text",
      label: "友链页加载失败标题",
      helpTitle: "友链页接口失败时的主标题",
      helpDescription: "用于友链列表区域的错误状态标题。",
      usageItems: [
        "友链页错误状态标题",
      ],
      optional: true,
    },
    {
      key: "circle_title",
      source: "extra",
      input: "text",
      label: "友链动态区标题",
      helpTitle: "友链页第二部分的大标题",
      helpDescription: "控制 Friend Circle 区域的标题。",
      usageItems: [
        "友链页动态区标题",
      ],
      optional: true,
    },
    {
      key: "statusLabel",
      source: "extra",
      input: "text",
      label: "友链动态区状态标签",
      helpTitle: "友链动态区标题右侧的小标签",
      helpDescription: "一般用于说明这里展示的是动态区或状态区。",
      usageItems: [
        "友链页动态区右上角标签",
      ],
      optional: true,
    },
    {
      key: "loadingLabel",
      source: "extra",
      input: "text",
      label: "友链页加载中文案",
      helpTitle: "友链页加载更多或加载中状态文案",
      helpDescription: "会用于友链页底部按钮加载态。",
      usageItems: [
        "友链页「加载更多」按钮的加载态",
      ],
      optional: true,
    },
    {
      key: "loadMoreLabel",
      source: "extra",
      input: "text",
      label: "友链页加载更多按钮",
      helpTitle: "友链页继续加载动态的按钮文案",
      helpDescription: "当友邻动态未全部显示时使用。",
      usageItems: [
        "友链页底部按钮",
      ],
      optional: true,
    },
    {
      key: "retryLabel",
      source: "extra",
      input: "text",
      label: "友链页重试按钮",
      helpTitle: "友链页错误状态的重试按钮文案",
      helpDescription: "用于友链卡片错误状态与动态区错误状态。",
      usageItems: [
        "友链页错误状态按钮",
      ],
      optional: true,
    },
    {
      key: "refreshLabel",
      source: "extra",
      input: "text",
      label: "友链页刷新按钮",
      helpTitle: "友链动态区刷新按钮文案",
      helpDescription: "用于友链动态区右上角刷新按钮本身的文字。",
      usageItems: [
        "友链页动态区刷新按钮",
      ],
      optional: true,
    },
    {
      key: "refreshAriaLabel",
      source: "extra",
      input: "text",
      label: "友链页刷新按钮辅助文案",
      helpTitle: "友链动态区刷新按钮的 aria / title 文案",
      helpDescription: "用于可访问性提示和鼠标悬停提示，建议写完整动作说明。",
      usageItems: [
        "友链页动态区刷新按钮 aria-label",
        "友链页动态区刷新按钮 title",
      ],
      optional: true,
    },
    {
      key: "randomPickerLabel",
      source: "extra",
      input: "text",
      label: "友链随机推荐说明",
      helpTitle: "随机推荐卡片上方的说明文案",
      helpDescription: "支持 `{days}` 占位符，例如：`从最近 {days} 天里随机挑一篇`。",
      usageItems: [
        "友链页随机推荐区说明文字",
      ],
      optional: true,
      placeholder: "从最近 {days} 天里随机挑一篇",
    },
    {
      key: "randomRefreshLabel",
      source: "extra",
      input: "text",
      label: "友链随机推荐刷新按钮",
      helpTitle: "随机推荐卡片右侧按钮文案",
      helpDescription: "点击后会重新抽取一篇最近友链文章。",
      usageItems: [
        "友链页随机推荐区按钮",
      ],
      optional: true,
    },
    {
      key: "randomEmptyTemplate",
      source: "extra",
      input: "text",
      label: "友链随机推荐空状态模板",
      helpTitle: "随机推荐区域暂无文章时的提示模板",
      helpDescription: "支持 `{days}` 占位符，例如：`最近 {days} 天还没有可展示的友链文章`。",
      usageItems: [
        "友链页随机推荐区空状态",
      ],
      optional: true,
      placeholder: "最近 {days} 天还没有可展示的友链文章",
    },
    {
      key: "summaryTemplate",
      source: "extra",
      input: "text",
      label: "友链动态区摘要模板",
      helpTitle: "友链动态标题下方的统计模板",
      helpDescription: "支持 `{sites}` 和 `{articles}` 占位符，例如：`{sites} 个站点 · 共 {articles} 条动态`。",
      usageItems: [
        "友链页动态区标题下方统计行",
      ],
      optional: true,
      placeholder: "{sites} 个站点 · 共 {articles} 条动态",
    },
    {
      key: "footerSummaryTemplate",
      source: "extra",
      input: "text",
      label: "友链页底部摘要模板",
      helpTitle: "友链页最底部的总结文案模板",
      helpDescription: "支持 `{sites}` 和 `{articles}` 占位符，例如：`已连接 {sites} 个站点，最近抓取 {articles} 条公开动态`。",
      usageItems: [
        "友链页底部总结文案",
      ],
      optional: true,
      placeholder: "已连接 {sites} 个站点，最近抓取 {articles} 条公开动态",
    },
  ],
  excerpts: [
    {
      key: "errorTitle",
      source: "extra",
      input: "text",
      label: "文摘页加载失败标题",
      helpTitle: "文摘列表接口失败时的标题",
      helpDescription: "用于文摘页错误状态卡片。",
      usageItems: [
        "文摘页错误状态标题",
      ],
      optional: true,
    },
    {
      key: "retryLabel",
      source: "extra",
      input: "text",
      label: "文摘页重试按钮",
      helpTitle: "文摘页错误状态重试按钮文案",
      helpDescription: "用于文摘页错误状态按钮。",
      usageItems: [
        "文摘页错误状态按钮",
      ],
      optional: true,
    },
    {
      key: "loadMoreLabel",
      source: "extra",
      input: "text",
      label: "文摘页加载更多文案",
      helpTitle: "文摘列表底部加载更多提示",
      helpDescription: "当文摘列表还有更多内容时显示。",
      usageItems: [
        "文摘页底部加载提示",
      ],
      optional: true,
    },
    {
      key: "modalCloseLabel",
      source: "extra",
      input: "text",
      label: "文摘弹窗关闭提示",
      helpTitle: "文摘弹窗关闭按钮的辅助文案",
      helpDescription: "用于关闭按钮的 aria-label，影响可访问性和读屏提示。",
      usageItems: [
        "文摘详情弹窗关闭按钮",
      ],
      optional: true,
    },
    {
      key: "commentsOpenLabel",
      source: "extra",
      input: "text",
      label: "文摘弹窗「查看评论」按钮",
      helpTitle: "文摘弹窗展开评论时的按钮前缀",
      helpDescription: "会自动在后面追加评论数量。",
      usageItems: [
        "文摘详情弹窗评论切换按钮",
      ],
      optional: true,
    },
    {
      key: "commentsCloseLabel",
      source: "extra",
      input: "text",
      label: "文摘弹窗「收起评论」按钮",
      helpTitle: "文摘弹窗评论展开后的按钮文案",
      helpDescription: "用于切换评论区关闭状态。",
      usageItems: [
        "文摘详情弹窗评论切换按钮",
      ],
      optional: true,
    },
  ],
  thoughts: [
    {
      key: "errorTitle",
      source: "extra",
      input: "text",
      label: "碎碎念页加载失败标题",
      helpTitle: "碎碎念列表接口失败时的标题",
      helpDescription: "用于碎碎念页错误状态。",
      usageItems: [
        "碎碎念页错误状态标题",
      ],
      optional: true,
    },
    {
      key: "retryLabel",
      source: "extra",
      input: "text",
      label: "碎碎念页重试按钮",
      helpTitle: "碎碎念页错误状态按钮文案",
      helpDescription: "用于碎碎念页的重试按钮。",
      usageItems: [
        "碎碎念页错误状态按钮",
      ],
      optional: true,
    },
    {
      key: "loadMoreLabel",
      source: "extra",
      input: "text",
      label: "碎碎念页加载更多文案",
      helpTitle: "碎碎念列表底部加载提示",
      helpDescription: "当碎碎念还有更多内容时显示。",
      usageItems: [
        "碎碎念页底部加载提示",
      ],
      optional: true,
    },
  ],
  guestbook: [
    {
      key: "promptTitle",
      source: "extra",
      input: "text",
      label: "留言板提示区标题",
      helpTitle: "留言板顶部说明卡片的标题",
      helpDescription: "位于留言板评论组件上方的提示区标题。",
      usageItems: [
        "留言板页顶部提示卡片",
      ],
      optional: true,
    },
    {
      key: "nameFieldLabel",
      source: "extra",
      input: "text",
      label: "留言板「昵称」标签",
      helpTitle: "留言提示区的昵称字段名",
      helpDescription: "用于提示区中介绍昵称输入框的前缀名称。",
      usageItems: [
        "留言板页提示卡片",
      ],
      optional: true,
    },
    {
      key: "contentFieldLabel",
      source: "extra",
      input: "text",
      label: "留言板「正文」标签",
      helpTitle: "留言提示区的正文字段名",
      helpDescription: "用于提示区中介绍正文输入框的前缀名称。",
      usageItems: [
        "留言板页提示卡片",
      ],
      optional: true,
    },
    {
      key: "submitFieldLabel",
      source: "extra",
      input: "text",
      label: "留言板「按钮」标签",
      helpTitle: "留言提示区的按钮字段名",
      helpDescription: "用于提示区中介绍提交按钮的前缀名称。",
      usageItems: [
        "留言板页提示卡片",
      ],
      optional: true,
    },
    {
      key: "namePlaceholder",
      source: "extra",
      input: "text",
      label: "留言板昵称占位词",
      helpTitle: "留言板昵称输入框 placeholder",
      helpDescription: "直接影响留言组件里的昵称输入提示。",
      usageItems: [
        "留言组件昵称输入框",
      ],
      optional: true,
    },
    {
      key: "contentPlaceholder",
      source: "extra",
      input: "text",
      label: "留言板正文占位词",
      helpTitle: "留言板正文输入框 placeholder",
      helpDescription: "直接影响留言组件里的正文输入提示。",
      usageItems: [
        "留言组件正文输入框",
      ],
      optional: true,
    },
    {
      key: "submitLabel",
      source: "extra",
      input: "text",
      label: "留言板提交按钮",
      helpTitle: "留言板提交动作按钮文案",
      helpDescription: "直接影响留言组件里的提交按钮文本。",
      usageItems: [
        "留言组件提交按钮",
      ],
      optional: true,
    },
    {
      key: "submittingLabel",
      source: "extra",
      input: "text",
      label: "留言板提交中按钮文案",
      helpTitle: "留言正在提交时的按钮文案",
      helpDescription: "用于留言组件提交中的状态文字。",
      usageItems: [
        "留言组件提交中状态",
      ],
      optional: true,
    },
    {
      key: "loadingLabel",
      source: "extra",
      input: "text",
      label: "留言板加载中文案",
      helpTitle: "留言组件加载中状态文案",
      helpDescription: "用于留言板评论列表尚未加载完成时。",
      usageItems: [
        "留言组件加载中状态",
      ],
      optional: true,
    },
    {
      key: "retryLabel",
      source: "extra",
      input: "text",
      label: "留言板重试按钮",
      helpTitle: "留言板错误状态重试按钮文案",
      helpDescription: "用于留言板评论组件的错误状态按钮。",
      usageItems: [
        "留言组件错误状态按钮",
      ],
      optional: true,
    },
  ],
  resume: [],
  calendar: [
    {
      key: "loadingLabel",
      source: "extra",
      input: "text",
      label: "日历加载中文案",
      helpTitle: "日历页加载中的提示",
      helpDescription: "用于日历右侧详情区域的加载提示。",
      usageItems: [
        "日历页侧栏加载态",
      ],
      optional: true,
    },
    {
      key: "retryLabel",
      source: "extra",
      input: "text",
      label: "日历重试按钮",
      helpTitle: "日历页错误状态按钮文案",
      helpDescription: "用于日历接口失败时的重试按钮。",
      usageItems: [
        "日历页错误状态按钮",
      ],
      optional: true,
    },
    {
      key: "todayLabel",
      source: "extra",
      input: "text",
      label: "日历「今日」标签",
      helpTitle: "右侧详情区默认标题",
      helpDescription: "在未选中具体日期时，侧栏标题会使用这段文字。",
      usageItems: [
        "日历页侧栏标题",
      ],
      optional: true,
    },
    {
      key: "errorTitle",
      source: "extra",
      input: "text",
      label: "日历加载失败标题",
      helpTitle: "日历页接口失败时的主提示",
      helpDescription: "用于日历右侧详情区的错误标题。",
      usageItems: [
        "日历页错误状态标题",
      ],
      optional: true,
    },
    {
      key: "selectedEmptyMessage",
      source: "extra",
      input: "textarea",
      label: "日历日期无记录文案",
      helpTitle: "选中某一天但没有内容时的提示",
      helpDescription: "区别于整个月没有数据时的空状态文案。",
      usageItems: [
        "日历页侧栏空状态",
      ],
      optional: true,
    },
    {
      key: "postTypeLabel",
      source: "extra",
      input: "text",
      label: "日历「帖子」类型标签",
      helpTitle: "日历事件类型标签之一",
      helpDescription: "用于图例和事件卡片中的帖子类型名称。",
      usageItems: [
        "日历页图例",
        "日历页事件卡片类型标签",
      ],
      optional: true,
    },
    {
      key: "diaryTypeLabel",
      source: "extra",
      input: "text",
      label: "日历「日记」类型标签",
      helpTitle: "日历事件类型标签之一",
      helpDescription: "用于图例和事件卡片中的日记类型名称。",
      usageItems: [
        "日历页图例",
        "日历页事件卡片类型标签",
      ],
      optional: true,
    },
    {
      key: "excerptTypeLabel",
      source: "extra",
      input: "text",
      label: "日历「文摘」类型标签",
      helpTitle: "日历事件类型标签之一",
      helpDescription: "用于图例和事件卡片中的文摘类型名称。",
      usageItems: [
        "日历页图例",
        "日历页事件卡片类型标签",
      ],
      optional: true,
    },
    {
      key: "weekdayLabels",
      source: "extra",
      input: "list",
      label: "星期标签列表",
      helpTitle: "日历顶栏的 7 个星期标题",
      helpDescription: "用换行或英文逗号分隔，一共 7 项，顺序为周一到周日。",
      usageItems: [
        "日历页星期表头",
      ],
      optional: true,
      placeholder: "周一\n周二\n周三\n周四\n周五\n周六\n周日",
    },
    {
      key: "monthLabels",
      source: "extra",
      input: "list",
      label: "月份标签列表",
      helpTitle: "日历页的 12 个月份标题",
      helpDescription: "用换行或英文逗号分隔，一共 12 项，顺序为 1 月到 12 月。",
      usageItems: [
        "日历页月份切换标题",
      ],
      optional: true,
      placeholder: "1月\n2月\n3月\n4月\n5月\n6月\n7月\n8月\n9月\n10月\n11月\n12月",
    },
  ],
};

export const getFieldsForPage = (pageKey: string): PageFieldDefinition[] => [
  ...SHARED_FIELDS,
  ...(PAGE_SPECIFIC_FIELDS[pageKey] ?? []),
];
