#!/usr/bin/env bash
set -euo pipefail

echo "==> 正在设置开发环境的端口号..."

# 参数解释：
# $1: 起始端口号
# $剩下的所有参数: 需要跳过的端口列表（可选）
find_free_port() {
  if [[ $# -lt 1 ]]; then
    echo "find_free_port: 没有指定起始的端口号" >&2
    return 1
  fi
  local port=$1
  shift || true
  local -A skip=()
  for p in "$@"; do skip[$p]=1; done
  # 端口已被占用 || 端口在跳过列表里
  while ss -tlnH "sport = :$port" | grep -q . || [[ -n "${skip[$port]:-}" ]]; do
    port=$((port + 1))
  done
  echo "$port"
}

BACKEND_PORT=$(find_free_port 8000)
FRONTEND_PORT=$(find_free_port 8080 "$BACKEND_PORT")
ADMIN_PORT=$(find_free_port 3001 "$BACKEND_PORT" "$FRONTEND_PORT")

# 将选定的端口写入 /.env.local，供后续的 dev-start.sh 和 Docker 构建使用
ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.env.local"
cat > "$ENV_FILE" <<EOF
# Auto-generated by setup-ports.sh — not tracked by git
AERISUN_PORT=$BACKEND_PORT
AERISUN_FRONTEND_PORT=$FRONTEND_PORT
AERISUN_ADMIN_PORT=$ADMIN_PORT
AERISUN_SITE_URL=http://localhost:$FRONTEND_PORT
VITE_FRONTEND_URL=http://localhost:$FRONTEND_PORT
AERISUN_FRONTEND_UPSTREAM=host.docker.internal:$FRONTEND_PORT
AERISUN_ADMIN_UPSTREAM=host.docker.internal:$ADMIN_PORT
EOF

echo "👉 进程端口已选定   backend:$BACKEND_PORT  frontend:$FRONTEND_PORT  admin:$ADMIN_PORT"
echo "👉 进程端口已写入到 $ENV_FILE"
