#!/usr/bin/env bash
set -euo pipefail

# Find a free TCP port starting from the given number.
find_free_port() {
  local port=${1:-8000}
  while ss -tlnH "sport = :$port" | grep -q .; do
    port=$((port + 1))
  done
  echo "$port"
}

BACKEND_PORT=$(find_free_port 8000)
FRONTEND_PORT=$(find_free_port 8080)
ADMIN_PORT=$(find_free_port 3001)

ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.env.local"

cat > "$ENV_FILE" <<EOF
# Auto-generated by setup-ports.sh — not tracked by git
AERISUN_PORT=$BACKEND_PORT
AERISUN_FRONTEND_PORT=$FRONTEND_PORT
AERISUN_ADMIN_PORT=$ADMIN_PORT
EOF

echo "Ports → backend:$BACKEND_PORT  frontend:$FRONTEND_PORT  admin:$ADMIN_PORT"
echo "Written to $ENV_FILE"
